#
# ESLint Configuration (YAML-Formatting)
#
env:     {jest: true, node: true}
extends: ['airbnb-base']
parser:  babel-eslint
plugins: ['import']
root:    true
rules:
  import/no-extraneous-dependencies: ["error",{"devDependencies": ["__tests__/**"]}]
  import/prefer-default-export:      0
  no-console:                        ["warn",{"allow": ["warn","error"]}]
  no-param-reassign:                 ["error",{"props": false}]
  no-use-before-define:              ["error",{"functions": false}]
